### ISSUE TITLE
Cmake files missing dependency in sample

### ISSUE THREAD

**Issue by sjk7** [a4z/libsl3#1]
sample does not build on my machine (Mint Sonya) due to missing dependency on -lpthread.

my fix: (~/scratch/libsl3/tests/sample/CMakeLists.txt)
////////////////////////////////////////////////////////////////////////////////////////////
ADD_EXECUTABLE( sl3_sample main.cpp )
TARGET_LINK_LIBRARIES( sl3_sample sl3 pthread ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})

ADD_EXECUTABLE( sl3_sample1 main1.cpp )
TARGET_LINK_LIBRARIES( sl3_sample1 sl3 pthread ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})

ADD_EXECUTABLE( sl3_sample2 main2.cpp )
TARGET_LINK_LIBRARIES( sl3_sample2 sl3 pthread ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})

ADD_EXECUTABLE( sl3_sample3 main3.cpp )
TARGET_LINK_LIBRARIES( sl3_sample3 sl3 pthread ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})

ADD_EXECUTABLE( sl3_sample4 main4.cpp )
TARGET_LINK_LIBRARIES( sl3_sample4 sl3 ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})

ADD_EXECUTABLE( sl3_sample5 main5.cpp )
TARGET_LINK_LIBRARIES( sl3_sample5 sl3 pthread ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})

ADD_EXECUTABLE( sl3_sample6 main6.cpp )
TARGET_LINK_LIBRARIES( sl3_sample6 sl3 pthread  ${sl3_sqlite3LIBS} ${OPTION_GCOVLIB})
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

**Comment by a4z** [comment]
thanks for the report!
since the default setup seems usually to work , see travis-ci, I would like to ask you
could you please provide some more information:
did you pass custom CMAKE_CXX_FLAGS to cmake when you cmaked the project? 
any other configurations or options that are not default?
